dist: trusty
language: scala
os: linux

jobs:
  include:
    - env: SBT_VERSION=1.3.10
      jdk: oraclejdk8

script:
  - sbt ^^$SBT_VERSION clean test
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs -r rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs -r rm

deploy:
  provider: script
  script: sbt 'set version := version.value.replace("-SNAPSHOT", "") + "." + System.getenv("TRAVIS_BUILD_NUMBER")' ^^$SBT_VERSION bundle:publish
  on:
    branch: master

cache:
  directories:
    - $HOME/.ivy2/cache/
    - $HOME/.sbt/boot/